
# This is a basic workflow to help you get started with Actions

# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build frontend docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          build-args: .
          tags: docker.pkg.github.com/${{ github.repository }}/jj-frontend-image-dev:latest
          
  azure-deploy:
    needs: build
    name: Deploy to Azure Dev VM
    runs-on: ubuntu-latest
    steps:
      - name: SSH Connection
        uses: appleboy/ssh-action@master
        env:
          REPO_OWNER: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          username: ${{ secrets.VM_USERNAME }}
          host: ${{ secrets.VM_HOST_DEV }}
          password: ${{ secrets.VM_PASSWORD }}
          script: |
            cd jibby/jibby-jabber-infra
            sudo docker-compose -f docker-compose-dev.yml down
            sudo docker system prune --all --force
            sudo docker-compose -f docker-compose-dev.yml up --detach
